/**
 * Unique actions names
 * @constant
 */
export const
    GET_CREDENTIALS_REQUEST = 'GET_CREDENTIALS_REQUEST',
    GET_CREDENTIALS_SUCCESS = 'GET_CREDENTIALS_SUCCESS',
    GET_CREDENTIALS_FAIL = 'GET_CREDENTIALS_FAIL',
    REMOVE_CREDENTIALS_REQUEST = 'REMOVE_CREDENTIALS_REQUEST',
    REMOVE_CREDENTIALS_SUCCESS = 'REMOVE_CREDENTIALS_SUCCESS',
    SAVE_CREDENTIALS_REQUEST = 'SAVE_CREDENTIALS_REQUEST',
    SAVE_CREDENTIALS_SUCCESS = 'SAVE_CREDENTIALS_SUCCESS',
    SAVE_CREDENTIALS_FAIL = 'SAVE_CREDENTIALS_FAIL',
    SET_PASSWORD = 'SET_PASSWORD',
    SET_USER = 'SET_USER';