export const
    GET_COLUMN_REQUEST = 'GET_COLUMN_REQUEST',
    GET_COLUMN_SUCCESS = 'GET_COLUMN_SUCCESS',
    GET_COLUMN_FAIL = 'GET_COLUMN_FAIL',
    SAVE_COLUMN_REQUEST = 'SAVE_COLUMN_REQUEST',
    SAVE_COLUMN_SUCCESS = 'SAVE_COLUMN_SUCCESS',
    SAVE_COLUMN_FAIL = 'SAVE_COLUMN_FAIL'