export const
    GET_TABLES_REQUEST = 'GET_TABLES_REQUEST',
    GET_TABLES_SUCCESS = 'GET_TABLES_SUCCESS',
    GET_TABLES_FAIL = 'GET_TABLES_FAIL',
    CLOSE_DATABASE_WINDOW = 'CLOSE_DATABASE_WINDOW',
    SET_DATABASE_WINDOW_STATE = 'SET_DATABASE_WINDOW_STATE';