/**
 * Unique actions names
 * @constant
 */
export const
    CLOSE_CREATE_DATABASE_MODAL = 'CLOSE_CREATE_DATABASE_MODAL',
    CLOSE_EDIT_DATABASE_MODAL = 'CLOSE_EDIT_DATABASE_MODAL',
    CLOSE_DELETE_DATABASE_MODAL = 'CLOSE_DELETE_DATABASE_MODAL',
    CREATE_DATABASE_REQUEST = 'CREATE_DATABASE_REQUEST',
    CREATE_DATABASE_SUCCESS = 'CREATE_DATABASE_SUCCESS',
    CREATE_DATABASE_FAIL = 'CREATE_DATABASE_FAIL',
    DELETE_DATABASE_REQUEST = 'DELETE_DATABASE_REQUEST',
    DELETE_DATABASE_SUCCESS = 'DELETE_DATABASE_SUCCESS',
    DELETE_DATABASE_FAIL = 'DELETE_DATABASE_FAIL',
    GET_DATABASES_REQUEST = 'GET_DATABASES_REQUEST',
    GET_DATABASES_SUCCESS = 'GET_DATABASES_SUCCESS',
    GET_DATABASES_FAIL = 'GET_DATABASES_FAIL',
    GET_DATABASE_REQUEST = 'GET_DATABASE_REQUEST',
    GET_DATABASE_SUCCESS = 'GET_DATABASE_SUCCESS',
    GET_DATABASE_FAIL = 'GET_DATABASE_FAIL',
    OPEN_CREATE_DATABASE_MODAL = 'OPEN_CREATE_DATABASE_MODAL',
    OPEN_EDIT_DATABASE_MODAL = 'OPEN_EDIT_DATABASE_MODAL',
    OPEN_DELETE_DATABASE_MODAL = 'OPEN_DELETE_DATABASE_MODAL',
    SET_DATABASE_NAME = 'SET_DATABASE_NAME',
    SET_DATABASE_OLD_NAME = 'SET_DATABASE_OLD_NAME',
    SET_FILTER = 'SET_FILTER',
    SET_SERVER_WINDOW_STATE = 'SET_SERVER_WINDOW_STATE',
    UPDATE_DATABASE_REQUEST = 'UPDATE_DATABASE_REQUEST',
    UPDATE_DATABASE_SUCCESS = 'UPDATE_DATABASE_SUCCESS',
    UPDATE_DATABASE_FAIL = 'UPDATE_DATABASE_FAIL';