/**
 * Unique actions names
 * @constant
 */
export const
    GET_DATABASES_REQUEST = 'GET_DATABASES_REQUEST',
    GET_DATABASES_SUCCESS = 'GET_DATABASES_SUCCESS',
    GET_DATABASES_FAIL = 'GET_DATABASES_FAIL',
    GET_DATABASE_REQUEST = 'GET_DATABASE_REQUEST',
    GET_DATABASE_SUCCESS = 'GET_DATABASE_SUCCESS',
    GET_DATABASE_FAIL = 'GET_DATABASE_FAIL',
    CREATE_DATABASE_REQUEST = 'CREATE_DATABASE_REQUEST',
    CREATE_DATABASE_SUCCESS = 'CREATE_DATABASE_SUCCESS',
    CREATE_DATABASE_FAIL = 'CREATE_DATABASE_FAIL',
    DELETE_DATABASE_REQUEST = 'DELETE_DATABASE_REQUEST',
    DELETE_DATABASE_SUCCESS = 'DELETE_DATABASE_SUCCESS',
    DELETE_DATABASE_FAIL = 'DELETE_DATABASE_FAIL',
    UPDATE_DATABASE_REQUEST = 'UPDATE_DATABASE_REQUEST',
    UPDATE_DATABASE_SUCCESS = 'UPDATE_DATABASE_SUCCESS',
    UPDATE_DATABASE_FAIL = 'UPDATE_DATABASE_FAIL',
    SET_CREATE_DATABASE_MODAL_VISIBILITY = 'SET_CREATE_DATABASE_MODAL_VISIBILITY',
    SET_DELETE_DATABASE_MODAL_VISIBILITY = 'SET_DELETE_DATABASE_MODAL_VISIBILITY',
    SET_EDIT_DATABASE_MODAL_VISIBILITY = 'SET_EDIT_DATABASE_MODAL_VISIBILITY',
    SET_SELECTED_DATABASE = 'SET_SELECTED_DATABASE',
    SET_SERVER_WINDOW_STATE = 'SET_SERVER_WINDOW_STATE',
    UPDATE_DATABASE_NAME = 'UPDATE_DATABASE_NAME',
    UPDATE_FILTER = 'UPDATE_FILTER';