export const
    GET_SETTINGS_REQUEST = 'GET_SETTINGS_REQUEST',
    GET_SETTINGS_SUCCESS = 'GET_SETTINGS_SUCCESS',
    GET_SETTINGS_FAIL = 'GET_SETTINGS_FAIL',
    SAVE_SETTINGS_REQUEST = 'SAVE_SETTINGS_REQUEST',
    SAVE_SETTINGS_SUCCESS = 'SAVE_SETTINGS_SUCCESS',
    SAVE_SETTINGS_FAIL = 'SAVE_SETTINGS_FAIL'