export const
    GET_COLUMNS_REQUEST = 'GET_COLUMNS_REQUEST',
    GET_COLUMNS_SUCCESS = 'GET_COLUMNS_SUCCESS',
    GET_COLUMNS_FAIL = 'GET_COLUMNS_FAIL',
    GET_INDEXES_REQUEST = 'GET_INDEXES_REQUEST',
    GET_INDEXES_SUCCESS = 'GET_INDEXES_SUCCESS',
    GET_INDEXES_FAIL = 'GET_INDEXES_FAIL',
    SET_COLUMNS_WINDOW_STATE = 'SET_COLUMNS_WINDOW_STATE'