export const
    GET_TABLES_REQUEST = 'GET_TABLES_REQUEST',
    GET_TABLES_SUCCESS = 'GET_TABLES_SUCCESS',
    GET_TABLES_FAIL = 'GET_TABLES_FAIL',
    SET_CREATE_TABLE_MODAL_VISIBILITY = 'SET_CREATE_TABLE_MODAL_VISIBILITY',
    SET_TABLE_COMMENT = 'SET_TABLE_COMMENT',
    SET_TABLE_NAME = 'SET_TABLE_NAME';
