/**
 * Unique actions names
 * @constant
 */
export const
    SAVE_CREDENTIALS_REQUEST = 'SAVE_CREDENTIALS_REQUEST',
    SAVE_CREDENTIALS_SUCCESS = 'SAVE_CREDENTIALS_SUCCESS',
    SAVE_CREDENTIALS_FAIL = 'SAVE_CREDENTIALS_FAIL',
    GET_CREDENTIALS_REQUEST = 'GET_CREDENTIALS_REQUEST',
    GET_CREDENTIALS_SUCCESS = 'GET_CREDENTIALS_SUCCESS',
    GET_CREDENTIALS_FAIL = 'GET_CREDENTIALS_FAIL'
