export const
    GET_BROWSE_REQUEST = 'GET_BROWSE_REQUEST',
    GET_BROWSE_SUCCESS = 'GET_BROWSE_SUCCESS',
    GET_BROWSE_FAIL = 'GET_BROWSE_FAIL',

    SET_FILTER_REQUEST = 'SET_FILTER_REQUEST',
    SET_FILTER_SUCCESS = 'SET_FILTER_SUCCESS',
    SET_FILTER_FAIL = 'SET_FILTER_FAIL'