export const
    GET_COLUMNS_REQUEST = 'GET_COLUMNS_REQUEST',
    GET_COLUMNS_SUCCESS = 'GET_COLUMNS_SUCCESS',
    GET_COLUMNS_FAIL = 'GET_COLUMNS_FAIL',
    SET_COLUMNS_WINDOW_STATE = 'SET_COLUMNS_WINDOW_STATE'
