/**
 * Unique actions names
 * @constant
 */
export const
    GET_DATABASES_REQUEST = 'GET_DATABASES_REQUEST',
    GET_DATABASES_SUCCESS = 'GET_DATABASES_SUCCESS',
    GET_DATABASES_FAIL = 'GET_DATABASES_FAIL',
    SET_DATABASES_WINDOW_STATE = 'SET_DATABASES_WINDOW_STATE'