export const
    GET_DATABASES_REQUEST = 'GET_DATABASES_REQUEST',
    GET_DATABASES_SUCCESS = 'GET_DATABASES_SUCCESS',
    GET_DATABASES_FAIL = 'GET_DATABASES_FAIL',
    SET_DATABASES_FILTER_REQUEST = 'SET_DATABASES_FILTER_REQUEST',
    SET_DATABASES_FILTER_SUCCESS = 'SET_DATABASES_FILTER_SUCCESS',
    SET_DATABASES_FILTER_FAIL = 'SET_DATABASES_FILTER_FAIL'