export const
    GET_DATABASE_REQUEST = 'GET_DATABASE_REQUEST',
    GET_DATABASE_SUCCESS = 'GET_DATABASE_SUCCESS',
    GET_DATABASE_FAIL = 'GET_DATABASE_FAIL',
    SET_DATABASE_WINDOW_STATE = 'SET_DATABASE_WINDOW_STATE'