/**
 * Unique actions names
 * @constant
 */
export const
    GET_DATABASES_REQUEST = 'GET_DATABASES_REQUEST',
    GET_DATABASES_SUCCESS = 'GET_DATABASES_SUCCESS',
    GET_DATABASES_FAIL = 'GET_DATABASES_FAIL',
    CREATE_DATABASE_REQUEST = 'CREATE_DATABASE_REQUEST',
    CREATE_DATABASE_SUCCESS = 'CREATE_DATABASE_SUCCESS',
    CREATE_DATABASE_FAIL = 'CREATE_DATABASE_FAIL',
    SET_CREATE_DATABASE_MODAL_VISIBILITY = 'SET_CREATE_DATABASE_MODAL_VISIBILITY',
    SET_SELECTED_DATABASE = 'SET_SELECTED_DATABASE',
    SET_SERVER_WINDOW_STATE = 'SET_SERVER_WINDOW_STATE',
    UPDATE_CREATE_DATABASE_TEXTBOX_NAME_VALUE = 'UPDATE_CREATE_DATABASE_TEXTBOX_NAME_VALUE';