export const
    GET_TABLES_REQUEST = 'GET_TABLES_REQUEST',
    GET_TABLES_SUCCESS = 'GET_TABLES_SUCCESS',
    GET_TABLES_FAIL = 'GET_TABLES_FAIL',
    SET_TABLES_WINDOW_STATE = 'SET_TABLES_WINDOW_STATE'