export const
    GET_STATUS_CONNECTIONS_REQUEST = 'GET_STATUS_CONNECTIONS_REQUEST',
    GET_STATUS_CONNECTIONS_SUCCESS = 'GET_STATUS_CONNECTIONS_SUCCESS',
    GET_STATUS_CONNECTIONS_FAIL = 'GET_STATUS_CONNECTIONS_FAIL'